<?php

namespace AppBundle\Repository;

/**
 * appreciationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class appreciationRepository extends \Doctrine\ORM\EntityRepository
{
}
