<?php

namespace AppBundle\Repository;

/**
 * format_apRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class format_apRepository extends \Doctrine\ORM\EntityRepository
{
}
