<?php

namespace AppBundle\Repository;

/**
 * prof_mat_classeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class prof_mat_classeRepository extends \Doctrine\ORM\EntityRepository
{
}
