# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: sha512
<<<<<<< HEAD
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
=======
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
>>>>>>> 2d45e216d0b60f1db3705f61b671cfb8362d2bc6
    providers:
        #in_memory:
            #memory: ~
        main : 
          entity : {class : AppBundle\Entity\User , property : username}
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            # activate different ways to authenticate
            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
            form_login:
                check_path: /login_check

                # the user is redirected here when they need to log in
                login_path: /login
                target_path_parameter: redirect_url
            logout:
                path:   /logout
                target: /
        
    access_control:
       # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/myspace, roles: [ROLE_ADMIN, ROLE_PROF] }
        - { path: ^/admin, roles: [ROLE_ADMIN] }