<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKhivpq3\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKhivpq3/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKhivpq3.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKhivpq3\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerKhivpq3\appProdDebugProjectContainer(array(
    'container.build_hash' => 'Khivpq3',
    'container.build_id' => 'fba631d2',
    'container.build_time' => 1519336412,
));
