<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRebuyhn\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRebuyhn/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRebuyhn.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRebuyhn\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerRebuyhn\appProdDebugProjectContainer(array(
    'container.build_hash' => 'Rebuyhn',
    'container.build_id' => 'a38d471b',
    'container.build_time' => 1519309839,
));
