<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN8seofy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN8seofy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerN8seofy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerN8seofy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerN8seofy\appProdProjectContainer(array(
    'container.build_hash' => 'N8seofy',
    'container.build_id' => '5f8c3125',
    'container.build_time' => 1519250857,
));
