<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOjwfs3s\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOjwfs3s/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerOjwfs3s.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerOjwfs3s\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerOjwfs3s\appProdDebugProjectContainer(array(
    'container.build_hash' => 'Ojwfs3s',
    'container.build_id' => '29f83a4b',
    'container.build_time' => 1519338381,
));
