<?php

namespace EDTBundle\Repository;

/**
 * carteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class carteRepository extends \Doctrine\ORM\EntityRepository
{
}
