<?php

namespace EDTBundle\Repository;

/**
 * formatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class formatRepository extends \Doctrine\ORM\EntityRepository
{
}
