<?php

namespace EDTBundle\Repository;

/**
 * professeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class professeurRepository extends \Doctrine\ORM\EntityRepository
{
}
