<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

$this->services['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/myspace'), array(0 => 'ROLE_ADMIN', 1 => 'ROLE_PROF'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/adminspace'), array(0 => 'ROLE_ADMIN'), NULL);

return $instance;
