<?php

namespace ParametrageBundle\Repository;

/**
 * AnneeScolairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeScolairesRepository extends \Doctrine\ORM\EntityRepository
{
}
