<?php

namespace ParametrageBundle\Repository;

/**
 * BusScolaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusScolaireRepository extends \Doctrine\ORM\EntityRepository
{
}
