<?php

namespace ParametrageBundle\Repository;

/**
 * CalendrierScolaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendrierScolaireRepository extends \Doctrine\ORM\EntityRepository
{
}
