<?php

namespace ParametrageBundle\Repository;

/**
 * CycleScolaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CycleScolaireRepository extends \Doctrine\ORM\EntityRepository
{
}
