<?php

namespace ParametrageBundle\Repository;

/**
 * CyclePedagogiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CyclePedagogiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
