<?php

namespace ParametrageBundle\Repository;

/**
 * NiveauScolaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveauScolaireRepository extends \Doctrine\ORM\EntityRepository
{
}
