<?php

namespace ParametrageBundle\Repository;

/**
 * SalleEspaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalleEspaceRepository extends \Doctrine\ORM\EntityRepository
{
}
