<?php

namespace ParametrageBundle\Repository;

/**
 * ServicesProposesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesProposesRepository extends \Doctrine\ORM\EntityRepository
{
}
