<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNkjapht\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNkjapht/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNkjapht.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNkjapht\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNkjapht\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Nkjapht',
    'container.build_id' => '1e7c774a',
    'container.build_time' => 1519336155,
));
