<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC3utgsw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC3utgsw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerC3utgsw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerC3utgsw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerC3utgsw\appDevDebugProjectContainer(array(
    'container.build_hash' => 'C3utgsw',
    'container.build_id' => 'd926e863',
    'container.build_time' => 1519252684,
));
