<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPw4aupo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPw4aupo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPw4aupo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPw4aupo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPw4aupo\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pw4aupo',
    'container.build_id' => 'dceb7987',
    'container.build_time' => 1519307062,
));
